blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', views.blog, name="blog"),
    path('search/', views.search_results, name="search_results"),
    path('post/<str:slug>/', views.post_detail, name="post_detail_url"),
    path('post/<str:slug>/leave_comment/', views.leave_comment, name="leave_comment"),
    path('category/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('register/', views.register, name="register"),
    path('contact/', views.contact, name="contact"),
    path('popular/', views.popular, name="popular"),
]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse

class Category(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('Ссылка', max_length=255, unique=True)
    image = models.ImageField('Картинка', blank=True)

    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug':self.slug})

    class Meta:
        verbose_name="Категория"
        verbose_name_plural = "Категории"
    
    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('Ссылка', max_length=255, unique=True)
    summary = models.TextField('Краткое описание')
    content = models.TextField('Описание')
    date = models.DateTimeField('Дата', default=timezone.now)
    image = models.ImageField('Картинка', blank=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    views = models.IntegerField('Просмотры', default=0)

    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug':self.slug})
    
    class Meta:
        verbose_name="Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField('Имя Автора', max_length=255)
    text = models.TextField('Текст комментария')
    date = models.DateTimeField('Дата комментария', default=timezone.now)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.author_name

class FeedBack(models.Model):
    name = models.CharField("Имя", max_length=255)
    last_name = models.CharField("Фамилия", max_length=255)
    email = models.EmailField("Email")
    phone = models.CharField("Телефон", max_length=255)
    message = models.TextField("Сообщение")
    date = models.DateTimeField("Дата", default = timezone.now)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
    
    def __str__(self):
        return self.name

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Никнейм", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Пароль", required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Повторите пароль", required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label = "Email", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label = "Имя", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label = "Фамилия", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))

    class Meta:
        model = User    
        fields = ("first_name", "last_name", "email", "password1", "password2", "username",)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return user

    

blog/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.urls import reverse
from .models import Post, Category, Comment, FeedBack
from .forms import RegisterForm
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

def index(request):
    news = Post.objects.order_by('-date')[:3]
    popular = Post.objects.filter(views__gt = 10)[:3]
    context = {'news':news, 'popular':popular}
    return render(request, 'blog/index.html', context)

def popular(request):
    popular = Post.objects.filter(views__gt = 10)
    return render(request, 'blog/popular.html', {'popular':popular})

def blog(request):
    news = Post.objects.order_by('-date')
    return render(request, 'blog/news.html', {'posts':news})

def search_results(request):
    query = request.GET.get('search')
    search_obj = Post.objects.filter(
        Q(title__icontains = query) | Q(summary__icontains = query)
    )
    return render(request, 'blog/search_result.html', {'query':query, 'search_obj':search_obj})

def post_detail(request, slug):
    post = Post.objects.get(slug__iexact=slug)
    post.views += 1
    post.save()
    return render(request, 'blog/post_detail.html', {'post':post})

def category_detail(request, slug):
    category = Category.objects.get(slug__iexact = slug)
    posts = Post.objects.order_by('-date')
    return render(request, 'blog/category_detail.html', {'category': category, 'posts': posts})

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RegisterForm()
    return render(request, 'blog/register.html', {'form':form})

def logout_view(request):
    logout(request)
    return redirect('index')

def leave_comment(request, slug):
    post = Post.objects.get(slug__iexact=slug)
    if request.user.is_authenticated:
        user = request.user.first_name
        post.comment_set.create(
            author_name = user, 
            text = request.POST.get('text')
            )
    else:
        post.comment_set.create(
            author_name = request.POST.get('name'),
            text = request.POST.get('text')
            )
    return redirect(reverse('post_detail_url', args=(slug,)))

def contact(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            first_name = request.user.first_name
            last_name = request.user.last_name
            email_user = request.user.email
            FeedBack.objects.create(
                name = first_name,
                last_name = last_name,
                email = email_user,
                phone = request.POST.get('phone'),
                message = request.POST.get('message')
            )
        else:
            FeedBack.objects.create(name = request.POST.get('name'),
                last_name = request.POST.get('last_name'),
                email = request.POST.get('email'),
                phone = request.POST.get('phone'),
                message = request.POST.get('message')
            )
    return render(request, 'blog/contact.html')
    

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        Сайт
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Главная <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog' %}">Новости</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Вход</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'popular' %}">Популярные</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                </ul>
                <form action="{% url 'search_results' %}" method="GET" class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" name="search" placeholder="Поиск..." aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
                </form>
            </div>
        </nav>
    </header>
    
        {% block content %}
        {% endblock %}
    <footer style="width: 100%; height: 150px; background: black"></footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for post in category.post_set.all %}
        <div class="col-md-3">
            <a href="{{post.categories.get_absolute_url}}">
                <p>{{post.categories.title}}</p>
            </a>
            <a href="{{post.get_absolute_url}}">
                <h3>{{post.title}}</h3>
            </a>
            {% if post.image.url != null %}
            <a href="{{post.get_absolute_url}}">
                <img src="{{post.image.url}}" alt="" style="width: 100%">
            </a>
            {% endif %}
            <p>{{post.summary}}</p>
            <em>{{post.date}}</em>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block title %}
Обратная связь
{% endblock %}

{% block content %}
<section class="container">
    <h1>Свяжитесь с нами!</h1>
    <div class="row">
        <div style="width: 100%">
            <form action="{% url 'contact' %}" method="POST">
                {% csrf_token %}
                {% if not user.is_authenticated %}
                <p>
                    <label>Имя</label>
                    <input type="text" name="name" class="form-control">
                    <label>Фамилия</label>
                    <input type="text" name="last_name" class="form-control">
                </p>
                <p>
                    <label>Email</label>
                    <input type="email" name="email" name="" id="" class="form-control">
                </p>
                {% endif %}
                <p>
                    <label>Телефон</label>
                    <input type="text" name="phone" class="form-control">
                </p>
                <p>
                    <label>Сообщение</label>
                    <textarea class="form-control" name="message" id="" cols="30" rows="10"></textarea>
                </p>
                <p>
                    <button class="btn btn-success" style="text-align: center;">Отправить</button>
                </p>
            </form>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
    Главная
{% endblock %}
{% load static %}
{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/1.jpg'%}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/2.png'%}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<div class="container-fluid">
    <div class="row">
        {% for post in news %}
        <div class="col-md-3">
            <h3>{{post.title}}</h3>
            {% if post.image.url != null %}
            <img src="{{post.image.url}}" alt="" style="width: 100%">
            {% endif %}
            <p>{{post.summary}}</p>
            <em>{{post.date|date:"D j M, Y"}}</em>
            <em>Просмотров: {{post.views}}</em>
        </div>
        {% endfor %}
    </div>
    <h3 style="text-align: center;">Популярные посты!</h3>
    <div class="row">
      {% for post in popular %}
      <div class="col-md-3">
          <h3>{{post.title}}</h3>
          {% if post.image.url != null %}
          <img src="{{post.image.url}}" alt="" style="width: 100%">
          {% endif %}
          <p>{{post.summary}}</p>
          <em>{{post.date|date:"D j M, Y"}}</em>
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

blog/templates/blog/news.html
{% extends 'blog/base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-3">
            <a href="{{post.categories.get_absolute_url}}">
                <p>{{post.categories.title}}</p>
            </a>
            <a href="{{post.get_absolute_url}}">
                <h3>{{post.title}}</h3>
            </a>
            {% if post.image.url != null %}
            <a href="{{post.get_absolute_url}}">
                <img src="{{post.image.url}}" alt="" style="width: 100%">
            </a>
            {% endif %}
            <p>{{post.summary}}</p>
            <em>{{post.date}}</em>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/popular.html
{% extends 'blog/base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for post in popular %}
        <div class="col-md-3">
            <a href="{{post.categories.get_absolute_url}}">
                <p>{{post.categories.title}}</p>
            </a>
            <a href="{{post.get_absolute_url}}">
                <h3>{{post.title}}</h3>
            </a>
            {% if post.image.url != null %}
            <a href="{{post.get_absolute_url}}">
                <img src="{{post.image.url}}" alt="" style="width: 100%">
            </a>
            {% endif %}
            <p>{{post.summary}}</p>
            <em>{{post.date}}</em>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}
{{post.title}}
{% endblock %}
{% block content %}
{% if post.image.url != null %}
<style>
    .bg-single{
        background: url('{{post.image.url}}'), rgba(0,0,0,.7);
        background-size: cover;
        background-blend-mode: multiply;
        height: 300px;
        text-align: center;
    }
</style>

<section class="container-fluid bg-single">
    <h1>{{post.title}}</h1>
    <p>{{post.summary}}</p>
</section>
{% endif %}
<section class="content">
    <div class="row">
        <h2 style="text-align:center">{{post.title}}</h2>
        {% if post.image.url != null %}
        <img style="text-align: center; width: 100%" src="{{post.image.url}}" alt="">
        {% endif %}
        <p>{{post.content}}</p>
        <em>{{post.date}}</em>
    </div>
</section>
<section>
    <h3>Комментариев: {{post.comment_set.count}}</h3>
    {% for comment in post.comment_set.all %}
    <div>
        <h3>{{comment.author_name}}</h3>
        <p>{{comment.text}}</p>
        <em>{{comment.date|date:"D j M, Y"}}</em>
    </div>
    {% endfor %}
</section>
<section class="content">
        <h3>Оставьте комментарий:</h3>
        <form action="{% url 'leave_comment' post.slug  %}" method="POST">
            {% csrf_token %}
            {% if not user.is_authenticated %}
            <input style="width: 100%" type="text" name="name" class="form-control">
            {% endif %}
            <textarea style="width: 100%" name="text" class="form-control" cols="30" rows="10"></textarea>
            <button type="submit" class="btn btn-success">Отправить</button>
        </form>
</section>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% block title %}
Форма регистрации
{% endblock %}

{% block content %}
<section class="container">
    <h1>Форма регистрации</h1>
    {% if user.is_authenticated %}
    Ухади
    {% else %}
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-success">Зарегестрироваться</button>
    </form>
    {% endif %}
</section>
{% endblock %}

blog/templates/blog/search_result.html
{% extends 'blog/base.html' %}

{% block title %}
    Поиск по запросу: {{query}}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>Поиск по запросу: {{query}}</h1>
    <div class="row">
        {% for post in search_obj %}
        <div class="col-md-3">
            <h3>{{post.title}}</h3>
            {% if post.image.url != null %}
            <img src="{{post.image.url}}" alt="" style="width: 100%">
            {% endif %}
            <p>{{post.summary}}</p>
            <em>{{post.date}}</em>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}